---
title: "make_CR_Table_1"
author: "Brian Burke"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(OEI)
library(knitr)
uid<-"Brian.Burke"
pwd<-"Burke.Brian"
```

## R Markdown

Test document to recreate Table 1 in the June 2019 Cruise Report

```{r getTable}
trawlInfo<-getTable(uid = uid, pwd=pwd, schemaName = "crepo", tableName = "Trawl Info")
stationInfo<-getTable(uid = uid, pwd=pwd, schemaName = "crepo", tableName = "Station Info")
```

```{r refine data}
trawlInfo<-trawlInfo[trawlInfo$`Cruise #`==62,]
stationInfo<-stationInfo[stationInfo$`Cruise #`==62,]
tableData<-merge(trawlInfo, stationInfo, by="Station Code")
finalData<-tableData[,c("Transect Name","Sample Date","Haul #","Station #","Depth (m)",
                        "Start Lat (decimal degrees)","Start Long (decimal degrees)",
                        "Trawling distance (km)","Bearing (degrees)",
                        "Start Time","End Time")]
```
## Make the Table

We'll see if this works:

```{r make table, echo=FALSE}
kable(finalData)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
